### PR TITLE
Convert to scala

### PR DESCRIPTION
**Pull request by BusyByte**

### CODE REVIEW

**Comment by BusyByte** [comment]
@raxod502 why is this continually assigning to the same element in the array all the chunks? 
only the last one in the chunkTemp list will end up getting assigned 

```
for (i=0; i<chunkTemp.size(); i++) {
     temporarySaveFile[twy][twx] = chunkTemp.get(i);
}
```

**Comment by raxod502** [comment]
Unfortunately, I have not the faintest idea.

Just looking at the structure of the surrounding code, maybe it was meant to be wrapped in `twy` and `twx` loops and an `if` statement to check if its `cx` and `cy` attributes were equal to `twx` and `twy`.

```
                                                for (twy=0; twy<2; twy++) {
                                                    for (twx=0; twx<2; twx++) {
                                                        for (i=chunkTemp.size()-1; i>-1; i--) {
                                                            if (chunkTemp.get(i).cx == twx && chunkTemp.get(i).cy == twy) {
                                                                chunkMatrix[twy][twx] = chunkTemp.get(i);
                                                                chunkTemp.remove(i);
                                                                break;
                                                            }
                                                        }
                                                        if (chunkMatrix[twy][twx] == null) {
                                                            if (temporarySaveFile[twy][twx] != null) {
                                                                chunkMatrix[twy][twx] = temporarySaveFile[twy][twx];
                                                            }
                                                            else {
                                                                chunkMatrix[twy][twx] = new Chunk(twx+ou, twy+ov);
                                                            }
                                                        }
                                                    }
                                                }
```

**Comment by raxod502** [comment]
If you really want to reduce the horrifyingness of the codebase, you might look at replacing the several hundred lines of block comments at the top with actual enums. Of course, replacing magic numbers is difficult since there are multiple different magic number systems over the same range, but I think if you changed the types of the arrays to use the appropriate enums, the compiler could help detect which enums should be used where.

I was going to see about doing that just for kicks, but then ENSIME had terrible documentation and I ran out of motivation to get it working.

**Comment by BusyByte** [comment]
I am planning on doimt that in  a few spot however I don't think I
understand it well enough.  I'll be asking some follow up questions.  Right
now when I run the program i get index out of bounds the x is like 1201 or
something and vx seems really high.  Going to write some specs to
troubleshoot.

**Comment by raxod502** [comment]
Ah yes, the mysterious ArrayIndexOutOfBoundsException when you click the mouse button. I never did figure out why that was happening. I have a hunch it might have something to do with the lighting or electricity system malfunctioning near the edge of the world, maybe.

**Comment by BusyByte** [comment]
it happens whenever I touch the mouse after the game loads, also I can't
edit the world name on startup

**Comment by BusyByte** [comment]
@raxod502 can you explain why resolvePowerMatrix and resolveLightMatrix both have `while(true)` and the only way to get out of this loop appears to catch a IndexOutOfBoundsException?  What are these methods doing and are they really using IndexOutOfBoundsException for control logic?

**Comment by raxod502** [comment]
T_T

Yes, it really does appear that those methods are using IndexOutOfBoundsException for control logic. I can't believe I missed this. It would have been great to put in the hall-of-shame in the README.

Unfortunately, my understanding of what those methods are supposed to be doing is rather less-than-zero. Because I abandoned this project (4+ years ago) when I was in the middle of a major refactoring on the electricity mechanics, it's likely that anything to do with the electricity mechanics makes no sense. That is why the game crashes when you click the mouse button, by the way: since I didn't use any version control, I was unable to find a version of the game that *wasn't* in the middle of a refactoring.

**Comment by BusyByte** [comment]
@raxod502 can you tell me what mousePos2 means?
It seems to be some kind of offset but not the mouse pos:
`mousePos2(0) =mouse() + player.ix - getWidth() / 2 + Player.width / 2`

Also I'm not sure what the player.x is being initialized to:
`new Player(WIDTH * 0.5 * BLOCKSIZE, 45)`

this x does not appear to be in window x  coordinates as width is 2400 and the window is only 800 wide?

**Comment by BusyByte** [comment]
@raxod502 you can also add invalid indexes coded into arrays of fixed length of 2 to your list of things not to do.
In 68e0662 I found some `mousePos[2]` and `mousePos[3]` when there should only ever indexes 0 and 1 since the  the array is only size 2

**Comment by raxod502** [comment]
> can you tell me what mousePos2 means?

I think it's the position of the mouse in the entire world as opposed to on-screen. `player.ix` is the chunk offset, I think.

> I'm not sure what the player.x is being initialized to

Halfway across the newly generated world.

> this x does not appear to be in window x coordinates

Correct, some coordinates are universal across the entire world. It's still measured in pixels, though.

> I found some `mousePos[2]` and `mousePos[3]` when there should only ever indexes 0 and 1 since the the array is only size 2

Lol.

**Comment by BusyByte** [comment]
@raxod502 I converted the commented out block id's to an enum.  let me know if ce24ec7 looks like you expected?

**Comment by raxod502** [comment]
Oh my god. It looks so different when the code has a semblance of sanity.

Does Scala let you just compare enum values directly for equality? If so, you could make the block arrays into arrays of the enum type, so you'd get type checking(?) to ensure you didn't miss any places. [I don't know a lot about Scala, having never done any development in it.]

Otherwise, looks fantastic.

**Comment by BusyByte** [comment]
@raxod502 So technically what I have is a sealed abstract class / trait with case objects and not an enumeration but it's the same idea with some benefits:
- I can compare directly with `==` or `!=`
- I can do pattern matching (think of switch statements on steroids without break statements)
  - directly on the values without duplicating the `==`
  - can write custom pattern extractors where I can say something like x match ChestBlock(id) => and get a bunch of conditions with one statement
  - since the base trait / abstract class is sealed to the file I can get exhaustiveness checks at compile time to make sure I've covered all the cases otherwise I get a compile warning saying I need to add more cases or a default match
- I can use a more mathematical approach with [typeclasses](http://danielwestheide.com/blog/2013/02/06/the-neophytes-guide-to-scala-part-12-type-classes.html) and if I wanted to say something like this:
  - Given implicit proof of a way to do an action B with A which inhabits the sum type (enum)  I can have this provided and proved at compile time and do action B on A (I'm working towards this)
  - Leads to killer decoupling and is actually better to do generics and proofs like this

Scala does have an Enumeration which is like Java enum but has some downsides also so I'm not using it.

**Comment by BusyByte** [comment]
@raxod502 I didn't answer your question about the array and the enum.  I can put the enum inside the array and refer to it by the base type but I'm hesitant to start out doing that.  I'm not sure if a pointer to an object would take up more space than the id `Int` and slow down lookups  Plus I don't want to change the program too much until I kind of understand the landscape a bit more.

**Comment by BusyByte** [comment]
@raxod502 few questions

What determines the length of this array being set in the ItemCollection?
```scala
 val tlist3 = Array[Short](0, 0, 0, 0, 0)
 cic = ItemCollection(CIC, tlist1, tlist2, tlist3)
```

It seems not to be the number of items in the collection looking at this there are only 4 items in the collection but we set the array to size 5?:
```scala
if (ic.icType == CIC) {
      if (ic.image == null) {
        ic.image = loadImage("interface/cic.png")
        (0 until 4).foreach { i =>
          updateIC(ic, i)
        }
      }
    }
```

Also what does `CIC` stand for?

**Comment by raxod502** [comment]
When in doubt look at the textures!

image

It appears that `CIC` stands for `Crafting Item Collection`, because this item-collection is for holding items currently being used in crafting. And indeed, there are five slots for items. But the last one is auto-generated by some horrifying code in `Inventory.updateIC` (it shows the result of the crafting), so I didn't run `updateIC` on it…

**Comment by BusyByte** [comment]
@raxod502 why would you need to create a new ItemCollection?  Shouldn't you be able to just reuse it once it's created?
```scala
ic = ItemCollection(ObduriteChest, icmatrix(l)(uy)(ux).ids, icmatrix(l)(uy)(ux).nums, icmatrix(l)(uy)(ux).durs)
```

**Comment by raxod502** [comment]
You mean why didn't I just store `ItemCollection` instances directly in the `icmatrix`? No idea.

**Comment by BusyByte** [comment]
@raxod502 from the type it looks like it is:
`var icmatrix: Array3D[ItemCollection]`

**Comment by raxod502** [comment]
Uh, well, in that case I have even less than no idea.

**Comment by BusyByte** [comment]
@raxod502 I wonder if it has to do with resetting these on ItemCollection, I'm thinking of moving these onto the TerraFrame class instead.
```
 var FUELP: Double                   = 0
  var SMELTP: Double                  = 0
  var F_ON: Boolean                   = false
```

**Comment by raxod502** [comment]
Mmm yeah that you mention it, that's probably it?

**Comment by BusyByte** [comment]
@raxod502 what are `worlds`, `kworlds`, and `fworlds`?

**Comment by raxod502** [comment]
Were that I knew.

In seriousness though, I think they are to do with the buffering system. They are 2x2 arrays because that's how many chunks could possibly be shown onscreen at the same time. `worlds` is the primary chunk images, and `fworlds` is the chunk images for the foreground (separate because the sprites have to be rendered between those two layers). I believe `kworlds` tells whether the chunk images can be killed since they have moved off-screen.

**Comment by raxod502** [comment]
This is so fascinating. The code all follows this twisted kind of logic, but it's so difficult to figure out what I must have been thinking at the time.

**Comment by BusyByte** [comment]
@raxod502 this helps me a lot not knowing anything at lease have a well placed guess

**Comment by ym1234** [comment]
Hey, This [commit](https://github.com/boskee/TerraFrame/commit/8551340269d9773906391f3acdd67f3365b40187) solves the ArrayIndexOutOfBounds exception (but it is in java not scala)

**Comment by BusyByte** [comment]
I'll check it out and translate it.  I'll let you know if I have any
questions about it.

**Comment by BusyByte** [comment]
@raxod502 can you tell me why non-tools need a tool speed?
```scala
(1 until items.length).foreach { i =>
      toolSpeedTemp.put(i.toShort, 0.175)
    }
```

**Comment by BusyByte** [comment]
@raxod502 also do you have the damage numbers for:
```
Magnetite Pick  169
Magnetite Axe  170
Magnetite Sword 171
Irradium Pick 172
Irradium Axe 173
Irradium Sword 174
```
I assume these should not be damage 1 which is default and missing.  Not sure where Magnetite and Irradium should be compared to the others.

**Comment by raxod502** [comment]
> why non-tools need a tool speed?

It's how fast you can place the block.

> do you have the damage numbers

Unfortunately, I don't. You'll have full creative liberty :)

> Not sure where Magnetite and Irradium should be compared to the others.

Me neither. It doesn't help that all the metals are listed in different orders in the different places where they show up (block IDs, item IDs, …).

**Comment by BusyByte** [comment]
@raxod502 can you explain why the recipe arrays have zeros in them?  That seems to be noitem or air
`(15, 15, 15, 0, 15, 0, 0, 15, 0, 154, 1), // Wooden Pick`

**Comment by raxod502** [comment]
It's a 3x3 grid, with the tenth entry being the result of the recipe and the eleventh being how many you get.

```
XXX
 X
 X
```

is a pickaxe. It's the same system as in Minecraft, although I don't blame you for being confused since this was ostensibly a Terraria clone.

**Comment by BusyByte** [comment]
@raxod502 why do you need a 3x3 grid for that recipe?
Isn't it just 5 stacks of wood gets you one wooden pickaxe?
If you need to draw it in a 3/3 grid to accept items I understand leaving the bottom ones blank but why does that blank need to be part of the recipe?

**Comment by BusyByte** [comment]
@raxod502 and you should add this to your list, I initially thought they were all ingredients until I got further into the code and saw them being assigned.

**Comment by raxod502** [comment]
image

In Minecraft, you can't put the items in any old orientation. The shape has to be correct. That's why this information has to be part of the recipe.

**Comment by BusyByte** [comment]
@raxod502 that seems pretty strict for me, harder to figure out the recipies, and harder to program, I suppose it lets you have the positions affect the outcome of the recipe and have different outcomes for the same ingredients.  I'll try to maintain this behavior as there is probably assets/rendering logic based on this I don't feel like changing at this point.

**Comment by BusyByte** [comment]
@raxod502 what does FRI1 and FRI2 mean and what is in them?

**Comment by BusyByte** [comment]
also FRN1 and FRN2

**Comment by BusyByte** [comment]
Also what is TORCHESL and TORCHESR?

**Comment by raxod502** [comment]
By cross-referencing with the item and block ID lists:

* FRI1 is items that can be smelted in a furnace (e.g. copper ore).
* FRI2 is the resulting items (e.g. copper ingot).
* FRN1 is how many copper ores you need for smelting to work.
* FRN2 is how many copper ingots you get per transaction.
* TORCHESL is the block that a torch block turns into when it's only supported by a wall on the left.
* TORCHESR is the block that a torch block turns into when it's only supported by a wall on the right.
* Amusingly, TORCHESB doesn't seem to be used *anywhere*.

**Comment by BusyByte** [comment]
@raxod502 can you tell me what these blocks of code are doing like at https://github.com/raxod502/TerraFrame/blob/master/src/TerraFrame.java#L4730

**Comment by raxod502** [comment]
Sorry, I've reached the end of my understanding. (And likely the understanding of my five-years-ago self, judging by this code just below.)

```
            print("[liek srsly man?] " + ir);
```

All I know is it has something to do with the [repeater logic](https://minecraft.gamepedia.com/Redstone_Repeater).

**Comment by BusyByte** [comment]
@raxod502 what is GSUPPORT?

**Comment by raxod502** [comment]
Looks like it's whether or not the block gets destroyed automatically when not supported from below.

**Comment by BusyByte** [comment]
@raxod502 hmm looks like it controls if sun is added `addSunLighting`?

**Comment by BusyByte** [comment]
@raxod502 could it be like growing supported?

**Comment by raxod502** [comment]
No, I believe it is actually marking where sunlight is added. You're supposed to get light level 15 anywhere there's direct sunlight (and it decreases by 1 per block), but my lighting algorithm was really inefficient so I actually only added level-15 light sources directly above solid blocks. `GSUPPORT` marks which blocks are considered solid for this purpose.

I guess I just hardcoded in the logic about blocks being destroyed automatically. Shame. This really looked like it until I looked at where it was used.

**Comment by raxod502** [comment]
I came back to this project because of the renaming (see https://github.com/raxod502/TerrariaClone#terraframe). And I saw this interesting commit, https://github.com/ym1234/TerraFrame/commit/450c4eb949e383f84581dd5190ada8ae84e9b77f, which somehow increases the framerate by like 50x.

**Comment by ym1234** [comment]
@raxod502 Moving from left to right requires generating the next chunk(?) which freezes the game ( but yes the frame rate when moving up and down is improved dramatically ).

Also you should rename the file called TerraFrame.java to TerrariaClone.java because I'm pretty sure it won't compile because class name must be equal to the file name ( I didn't test though)

**Comment by raxod502** [comment]
@ym1234 You are right, although it's not generating the chunk which is slow, but rendering it (because I had no idea how to render things efficiently). Also, you're right. I was going to rename TerraFrame.java, but then didn't. Oops.

**Comment by BusyByte** [comment]
So what I've heard of doing is not draw to the screen directly but have N
back buffers and draw the back buffer when it's ready.  Then you render
(flip) the whole back buffer at once.  You can also use clipping and
overdraw parial sections if.they are cut off.  I'll check out that commit
when I get time.  Been busy with my job recently.

**Comment by BusyByte** [comment]
@raxod502  @ym1234 I wonder if the init method was getting called twice.  I think when you add the Applet component to the JFrame it was probably calling init for you.  You then called it afterwards in the main method.  Switching to JPanel it looks like it doesn't have an init method.  It's actually complaining that I'm overriding nothing now.  That would be my guess, either that or JPanel is just better optimized than JApplet.

**Comment by BusyByte** [comment]
@raxod502 I introduce an enum for Layer in 9c23ea9 but I was wonder what each Layer0, Layer1, Layer2 were actually used for or denoted so I could name the enum names with a little more meaning.
Can you elaborate on the details of each Layer?

**Comment by raxod502** [comment]
Background, primary layer, foreground. In Terraria you can have background walls, and I also added foreground tiles in TerraFrame. The only layer with collision detection is the primary layer.

**Comment by BusyByte** [comment]
@raxod502 what is the value in BLOCKLIGHTS?  the key seems to be block id but I was wondering if the value seems to be some kind of light intensity?

**Comment by BusyByte** [comment]
@raxod502 I'm also wondering why if blocks have zero light intensity the block would be considered empty 
```
 public boolean empty(int x, int y) {
        return ((blocks[0][y][x] == 0 || BLOCKLIGHTS.get(blocks[0][y][x]) == 0) &&
                (blocks[1][y][x] == 0 || BLOCKLIGHTS.get(blocks[1][y][x]) == 0) &&
                (blocks[2][y][x] == 0 || BLOCKLIGHTS.get(blocks[2][y][x]) == 0));
    }
```
It would seem to me that the empty should be if the intensity greater than zero or if the block is air it should be empty?  The light block light check here seems backwards to me?

**Comment by raxod502** [comment]
> what is the value in BLOCKLIGHTS? the key seems to be block id but I was wondering if the value seems to be some kind of light intensity?

Yes, light values range from 0 to 21 (although it's not a hard maximum), with sunlight providing a level of 19. The light level decreases by 1 for each square traveled away from a source.

> I'm also wondering why if blocks have zero light intensity the block would be considered empty

It's hard to say given that the `empty` method is not used anywhere.

**Pull request merged**
